apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyterhub-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyterhub-pod-reader-binding
subjects:
  - kind: ServiceAccount
    name: hub
    namespace: jupyter
roleRef:
  kind: ClusterRole
  name: jupyterhub-pod-reader
  apiGroup: rbac.authorization.k8s.io
