apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jupyter
resources:
  - namespace.yaml
  - user-home-pvc.yaml
  - jupyterhub-namespaces-rbac.yaml # Optional: if you want to manage RBAC declaratively here
helmCharts:
  - name: jupyterhub
    repo: https://hub.jupyter.org/helm-chart/
    releaseName: jupyterhub
    namespace: jupyter
    version: 4.0.0
    valuesFile: values.yaml
