apiVersion: v1
kind: Secret
metadata:
  name: hub-secret-overrides
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
data: {}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hub-secret-overrides
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: hub-secret-overrides
    creationPolicy: Merge
    template:
      data:
        values.yaml: |
          hub:
            config:
              GenericOAuthenticator:
                client_secret: {{.client_secret}}
  data:
    - secretKey: client_secret
      remoteRef:
        key: ${[.vars.aws.secretStores.eodhp.name]}
        property: oauth2-proxy-workspaces.config.clientSecret
