hub:
  baseUrl: /notebooks
  extraConfig:
    00-kubespawner-namespaces: |
      # Enable per-user namespaces. When a user logs in,
      # the {username} placeholder is replaced with their login name.
      c.KubeSpawner.enable_user_namespaces = True
      c.KubeSpawner.user_namespace_template = "{username}"
      c.KubeSpawner.hub_connect_url = "http://hub.jupyter.svc.cluster.local:8081"

proxy:
  service:
    type: ClusterIP

singleuser:
  image:
    name: "quay.io/jupyter/datascience-notebook"
    tag: "r-4.3.3"
  storage:
    type: static
    # When using static storage mode, the PVC "user-home-pvc" must be pre-created.
    homeMountPath: /home/{username}
    static:
      pvcName: user-home-pvc
      subPath: "{username}"
  profileList:
    - display_name: "Data Science (Python)"
      description: "Standard Python DS environment."
      default: true
    - display_name: "Jupyter/Base-notebook"
      description: "Base Notebook environment."
      kubespawner_override:
        image: "quay.io/jupyter/base-notebook:lab-4.3.5"
    # - display_name: "Julia Environment"
    #   description: "Julia-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/julia-notebook:lab-4.3.5"
    # - display_name: "R Environment"
    #   description: "R-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/r-notebook:r-4.4.2"
    # - display_name: "Scipy Environment"
    #   description: "Scipy-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/scipy-notebook:python-3.12"
    # - display_name: "Tensorflow Environment"
    #   description: "Tensorflow-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/tensorflow-notebook:ubuntu-24.04"
    # - display_name: "PySpark Environment"
    #   description: "PySpark-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/pyspark-notebook:hub-5.2.1"
    # - display_name: "Pytorch Environment"
    #   description: "Pytorch-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/pytorch-notebook:cuda11-ubuntu-24.04"
