hub:
  baseUrl: /notebooks

proxy:
  service:
    type: ClusterIP

singleuser:
  image:
    name: "quay.io/jupyter/datascience-notebook"
    tag: "r-4.3.3"
  storage:
    type: static
    homeMountPath: /home/{username}
    static:
      pvcName: user-home-pvc
      subPath: "{username}"
  profileList:
    - display_name: "Data Science (Python)"
      description: "Standard Python DS environment."
      default: true
    - display_name: "Jupyter/Base-notebook"
      description: "Base Notebook environment."
      kubespawner_override:
        image: "quay.io/jupyter/base-notebook:lab-4.3.5"
    - display_name: "Julia Environment"
      description: "Julia-based notebook environment."
      kubespawner_override:
        image: "quay.io/jupyter/julia-notebook:lab-4.3.5"
