hub:
  baseUrl: /notebooks
  extraConfig:
    00-kubespawner-namespaces: |
      # Enable per-user namespaces:
      c.KubeSpawner.enable_user_namespaces = True
      # The new namespace will be named after the username (e.g. "shahid")
      c.KubeSpawner.user_namespace_template = "{username}"
      # This is the internal URL that user pods use to connect back to the hub
      c.KubeSpawner.hub_connect_url = "http://hub.jupyter.svc.cluster.local:8081"

proxy:
  service:
    type: ClusterIP

singleuser:
  image:
    name: "quay.io/jupyter/datascience-notebook"
    tag: "r-4.3.3"
  # Use dynamic storage so that a PVC is automatically created in the user’s namespace.
  storage:
    type: dynamic
    homeMountPath: /home/{username}
    dynamic:
      # The storage class must support dynamic provisioning. In minikube, this is usually "standard".
      storageClass: standard
      # The size allocated per user
      capacity: 10Gi
      # A naming template to generate the PVC name.
      # {username} is replaced by the user's login name and {servername} by the spawned server name.
      pvcNameTemplate: claim-{username}--{servername}
  profileList:
    - display_name: "Data Science (Python)"
      description: "Standard Python DS environment."
      default: true
    - display_name: "Jupyter/Base-notebook"
      description: "Base Notebook environment."
      kubespawner_override:
        image: "quay.io/jupyter/base-notebook:lab-4.3.5"
    # - display_name: "Julia Environment"
    #   description: "Julia-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/julia-notebook:lab-4.3.5"
    # - display_name: "R Environment"
    #   description: "R-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/r-notebook:r-4.4.2"
    # - display_name: "Scipy Environment"
    #   description: "Scipy-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/scipy-notebook:python-3.12"
    # - display_name: "Tensorflow Environment"
    #   description: "Tensorflow-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/tensorflow-notebook:ubuntu-24.04"
    # - display_name: "PySpark Environment"
    #   description: "PySpark-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/pyspark-notebook:hub-5.2.1"
    # - display_name: "Pytorch Environment"
    #   description: "Pytorch-based notebook environment."
    #   kubespawner_override:
    #     image: "quay.io/jupyter/pytorch-notebook:cuda11-ubuntu-24.04"
